### PR TITLE
Fix typos in comments and documentation

### PR DESCRIPTION
**Pull request by aerostitch**
Hi,

I found some typos while reading the documentation so I ended up running a tool called `misspell` on the repo that basically fixes common misspells.
Reviewed the result, did some changes, but I think we should be ok with what's left here.

Let me know if you want to break this change into smaller changes or if there are some elements I might have missed.

Thanks
Jospeh

### CODE REVIEW

**Comment by wtarreau** [comment]
Hello,

thanks for doing all this work! It will definitely have to be spit : 
  - one or more patches for the documentation file(s) so that we can backport them to stable branches,
    you can (and should) tag them as "DOC"
  - one patch per subsystem for user-visible errors, such as in error messages, tagged "MINOR"
    so that we can selectively decide whether we want to backport them or not (for instance, sometimes
    it could cause some issues with existing tools configured to match a string in a message)
  - one patch per subsystem for invisible changes such as code comments, tagged "CLEANUP".
    Having them per subsystem will help respective maintainers to decide whether to take/revert
    them and/or backport them if that helps with future backports of fixes due to the context.

In any case, please carefully read the file named CONTRIBUTING, and send your patch series to the mailing list.

Thank you!

**Comment by lukastribus** [comment]
This was supposed to trigger the PR bot, but that broke when I moved it to a different server. Fixing now.

**Comment by lukastribus** [comment]
This is an automated message.

The haproxy project does not review or merge pull requests on GitHub (please see CONTRIBUTING).

Your patch or patchseries will be forwarded to the haproxy mailing list where it can be reviewed (you will be CC'ed).

This PR will be closed automatically.

**Comment by aerostitch** [comment]
Lol! Sending patches via email is so last century! :rofl:

**Pull request closed without merging**
