### PR TITLE
20231027 mux2mux quic 1

### PR DESCRIPTION
**Pull request by Valen1393**
Hey 
Sudahlah gak usah jadi pecundang
Email gue Lo ambil
Semua Lo retas 
Kalau mau tetang gue
Panggil gue diskusi bareng 
semakin gue di intimidasi 
Semakin gue membara
Kalian akan liat kedepannya 
Dan kalian akan mengerti siapa yang kalian hadapi saat ini.

### CODE REVIEW

**Comment by lukastribus** [comment]
This is an automated message.

The haproxy project does not review or merge pull requests on GitHub (please see CONTRIBUTING).

Your patch or patchseries will be forwarded to the haproxy mailing list where it can be reviewed (you will be CC'ed).

This PR will be closed automatically.

**Comment by wtarreau** [comment]
This looks like a strange spam, or a serious manipulation mistake. If this is a manipulation error, please comment here to explain what you attempted to do, or preferably on the mailing list.

**Comment by wlallemand** [comment]
Could be a stolen account, I'm seeing that this account created https://github.com/haproxy/haproxy/pull/2661 in the past.

**Comment by wtarreau** [comment]
Yeah I noticed the same, and the comments above look like scam threads, which make no sense from a real account.

**Pull request closed without merging**
